[project]
name = "tts-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coqui-tts>=0.27.0",
    "fastapi>=0.116.1",
    "hangul-romanize>=0.1.0",
    "python-multipart>=0.0.20",
    "uvicorn>=0.35.0",
]
